[tool.poetry]
name = "doker1"
version = "0.1.0"
description = ""
authors = ["lebedev-eo"]

[tool.poetry.dependencies]
python = "3.9.*"
requests = "^2.26.0"
Flask = "^2.0.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
